### ISSUE TITLE
Suggestions for pipeline with manual dependencies

### ISSUE THREAD

**Issue by rparrish** [whipson/maestro#105]
Wondering if you have any suggestions for configuring a maestro pipeline that has a manual dependency. 

I'd like to schedule an ETL pipeline to run once a week after a new data file has been downloaded manually from a legacy reporting system. For example, the pipeline would be scheduled to start on Monday mornings to run every hour until it completes the entire pipeline one time. If a new extract file has been updated, the pipeline would run once and then wait until the next week to run again. If the file has not been updated, the pipeline would  try again at the next hour. 

So far, I've tried using `stop()` in the pipeline if the modification time on the extract file is too old. This interrupts the pipeline as expected, but the next scheduled time increments to the next week instead of attempting to run again. 

Here's a minimal working example with the roxygen2 tags: 

```r
#' Example ETL pipeline
#' @maestroFrequency 1 week
#' @maestroStartTime 2024-08-01 07:30
#' @maestroTz America/Los_Angeles

my_ETL_refresh <- function() {
        pipeline_file <- "path/to/pipeline_file.R
        source(pipeline_file)
}
```

**Comment by whipson** [comment]
Maestro is best for pipelines that you want to run on a regular interval (e.g., hourly, weekly) regardless of external dependencies and conditions. In your case, you'd probably need to run the pipeline every hour and then use conditional logic in the pipeline itself to determine whether to execute the rest of the pipeline. I'm thinking something like this:

```
#' Example ETL pipeline
#' @maestroFrequency 1 hour
#' @maestroStartTime 2024-08-01 07:30
#' @maestroTz America/Los_Angeles

my_ETL_refresh <- function() {

        # Add conditional logic to check for new extract file
        if (file.exists('extract_file')) {
              pipeline_file <- "path/to/pipeline_file.R
              source(pipeline_file)
        }
}
```

In this case, the pipeline will do nothing if there's no new extract file. It still needs to check every hour and will check hourly even if the processing for that week has already completed. You may be able to use some additional conditionals to have the pipeline do nothing if it's already run that week. In general, event-based execution isn't yet possible in maestro. 

It's not related but I'm curious as to why your pipeline does a `source` to another R script. Is there a reason why the code is not inside the pipeline itself?

**Comment by rparrish** [comment]
Thanks for the suggestion and I can see how that would work. 

Regarding the `source()` method, this is primarily due to having a large number of existing pipelines in separate repositories.  The pattern actually used for this looks more like this, where the `{tryCatchLog}` package is used as a wrapper to generate more informative details about any failures. 
 
```r
    options(keep.source = TRUE)
    tryCatchLog( 
        source(pipeline_file), 
        include.full.call.stack = FALSE
    )
```
Again, thanks for the help.
